task: detection

num_classes: 5
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: 
    ann_file: 
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 32
  num_workers: 0
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: 
    ann_file: 
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 32
  num_workers: 0
  drop_last: False


test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: 
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 0
  drop_last: False