__include__: [
  # '../dataset/coco_detection.yml',
  # '../dataset/coco_detection.yml',
  # '../dataset/pcb7fs_detection.yml',
  '../dataset/pcb73_detection.yml',
  # '../dataset/pcb7_detection.yml',
  # '../dataset/pcb14_detection.yml',
  # '../dataset/pcb11_05_detection.yml',
  # '../dataset/pcbpk_detection.yml',
  # '../dataset/pcbpk2_detection.yml',
  # '../dataset/coco_detection.yml',
  # '../dataset/pcbpkfull_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_coco


PResNet:
  depth: 18
  freeze_at: 0
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


epoches: 400 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 380
  collate_fn:
    scales: ~